server:
  port: 7004 #服务注册中心端口号
eureka:
  instance:
    hostname: eureka7004 #服务注册中心IP地址
    prefer-ip-address: false
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
spring:
  application:
    name: eureka-server